services:
  sensor:
    build: .
    command: python3 sensor.py
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_DOMAIN_ID=0

  controller:
    build: .
    command: python3 controller.py
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_DOMAIN_ID=0
    depends_on:
      - sensor
